Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np
import pandas as pd


In [2]:
def ATV(matrix,n,increase):
    if increase:
        matrix1=([s**i for s in matrix for i in range (n)])
    else:
        matrix1=([s**(n-1-i) for s in matrix for i in range (n)])
    return np.matrix(matrix1).reshape(len(matrix),n)
        

In [3]:
x=np.array([1,2,3,4])

In [4]:
x

array([1, 2, 3, 4])

In [5]:
ATV(x,4,True)

matrix([[ 1,  1,  1,  1],
        [ 1,  2,  4,  8],
        [ 1,  3,  9, 27],
        [ 1,  4, 16, 64]])

In [6]:
ATV(x,4,False)

matrix([[ 1,  1,  1,  1],
        [ 8,  4,  2,  1],
        [27,  9,  3,  1],
        [64, 16,  4,  1]])

In [7]:
# 2. To find the moving average

In [8]:
def moving_average(a, k) :
    x=[]
    for i in range (len(a)-k+1):
        s=np.sum(a[i:k+i])/k
        x.append(s)
    
    print(f"Moving average sequence has {len(x)} values")
    for i in range(0,len(x)):
        print(f"y{i+1}={x[i]}")

In [9]:
ar=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [10]:
moving_average(ar,3)

Moving average sequence has 11 values
y1=5.0
y2=4.666666666666667
y3=5.666666666666667
y4=6.666666666666667
y5=9.666666666666666
y6=28.666666666666668
y7=49.333333333333336
y8=72.66666666666667
y9=84.0
y10=93.33333333333333
y11=116.33333333333333
